//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_Projekt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp_Projekt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj:.
        /// </summary>
        public static string Broj {
            get {
                return ResourceManager.GetString("Broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zabijenih golova u toj utakmici:.
        /// </summary>
        public static string BrojZabGol {
            get {
                return ResourceManager.GetString("BrojZabGol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih kartona u toj utakmici:.
        /// </summary>
        public static string BrojŽutih {
            get {
                return ResourceManager.GetString("BrojŽutih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite prvenstvo:.
        /// </summary>
        public static string ChooseChampionship {
            get {
                return ResourceManager.GetString("ChooseChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik:.
        /// </summary>
        public static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        public static string Croatian {
            get {
                return ResourceManager.GetString("Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika golova:.
        /// </summary>
        public static string DifGoals {
            get {
                return ResourceManager.GetString("DifGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa kod.
        /// </summary>
        public static string FifaCode {
            get {
                return ResourceManager.GetString("FifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijeli zaslon način rada.
        /// </summary>
        public static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string Ime {
            get {
                return ResourceManager.GetString("Ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan.
        /// </summary>
        public static string Kapetan {
            get {
                return ResourceManager.GetString("Kapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško prvenstvo.
        /// </summary>
        public static string ManChamp {
            get {
                return ResourceManager.GetString("ManChamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zabijenih golova:.
        /// </summary>
        public static string NumGoals {
            get {
                return ResourceManager.GetString("NumGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj primljenih golova:.
        /// </summary>
        public static string NumGoalsTaken {
            get {
                return ResourceManager.GetString("NumGoalsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj poraza:.
        /// </summary>
        public static string NumLoses {
            get {
                return ResourceManager.GetString("NumLoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj odigranih utakmica:.
        /// </summary>
        public static string NumMatchesPlayed {
            get {
                return ResourceManager.GetString("NumMatchesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj neriješenih:.
        /// </summary>
        public static string NumTies {
            get {
                return ResourceManager.GetString("NumTies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj pobjeda:.
        /// </summary>
        public static string NumWins {
            get {
                return ResourceManager.GetString("NumWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string Pozicija {
            get {
                return ResourceManager.GetString("Pozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite način prikaza:.
        /// </summary>
        public static string SettingsDisplayMode {
            get {
                return ResourceManager.GetString("SettingsDisplayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija:.
        /// </summary>
        public static string SettingsResolution {
            get {
                return ResourceManager.GetString("SettingsResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tim detalji.
        /// </summary>
        public static string TeamDetails {
            get {
                return ResourceManager.GetString("TeamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv:.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prozorski način rada.
        /// </summary>
        public static string WindowMode {
            get {
                return ResourceManager.GetString("WindowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko prvenstvo.
        /// </summary>
        public static string WomanChamp {
            get {
                return ResourceManager.GetString("WomanChamp", resourceCulture);
            }
        }
    }
}
