//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_OOP_Projekt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsForms_OOP_Projekt.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostujući tim.
        /// </summary>
        internal static string MatchesDataGridViewAwayTeam {
            get {
                return ResourceManager.GetString("MatchesDataGridViewAwayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domaći tim.
        /// </summary>
        internal static string MatchesDataGridViewHomeTeam {
            get {
                return ResourceManager.GetString("MatchesDataGridViewHomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string MatchesDataGridViewLocation {
            get {
                return ResourceManager.GetString("MatchesDataGridViewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj posjetitelja.
        /// </summary>
        internal static string MatchesDataGridViewVisitors {
            get {
                return ResourceManager.GetString("MatchesDataGridViewVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        internal static string PlayerDataGridViewImage {
            get {
                return ResourceManager.GetString("PlayerDataGridViewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime.
        /// </summary>
        internal static string PlayerDataGridViewName {
            get {
                return ResourceManager.GetString("PlayerDataGridViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova.
        /// </summary>
        internal static string PlayerDataGridViewNumGoals {
            get {
                return ResourceManager.GetString("PlayerDataGridViewNumGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj crvenih kartona.
        /// </summary>
        internal static string PlayerDataGridViewNumRed {
            get {
                return ResourceManager.GetString("PlayerDataGridViewNumRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih kartona.
        /// </summary>
        internal static string PlayerDataGridViewNumYellow {
            get {
                return ResourceManager.GetString("PlayerDataGridViewNumYellow", resourceCulture);
            }
        }
    }
}
